name: Pull Request Submitted Telegram Notification

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  pr_submitted_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send "PR approved" notifications
        if: github.event.review.state == 'approved'
        uses: WildEgor/tg-notification-action@v1.1.0
        with:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_TO }}
          MESSAGE: |
            Action: 🆗 ${{ github.actor }} approve PR
            Title: [${{ github.event.pull_request.title }}]
            Repository: ${{ github.repository }}
            Branch: ${{ steps.branch_name.outputs.branch }}
            See: [Link](${{ github.event.pull_request.html_url }})
          MENTIONS: ${{ toJson(github.event.pull_request.assignees) }}
          GITHUB2PROVIDER_MAP: ${{ secrets.TELEGRAM_USERS_MAP }}

      - name: Send "PR need updates" notification
        if: github.event.review.state == 'changes_requested'
        uses: WildEgor/tg-notification-action@v1.1.0
        with:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_TO }}
          MESSAGE: |
            Action: ☠️ ${{ github.event.pull_request.user.login }} request changes for PR
            Title: [${{ github.event.pull_request.title }}]
            Repository: ${{ github.repository }}
            Branch: ${{ github.event.pull_request.base.ref }}
            See: [Link](${{ github.event.pull_request.html_url }})
          MENTIONS: ${{ toJson(github.event.pull_request.assignees) }}
          GITHUB2PROVIDER_MAP: ${{ secrets.TELEGRAM_USERS_MAP }}
